[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "HbooBERomh6WwUy255utj1Uwu6WNgYeS7NXKfg7cWwe2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alkimo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
